spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9001"
      client:
        registration:
          client-app:
            provider: spring
            client-id: client-app
            client-secret: sonia##11
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8580/authorized"
            scope:
              - openid
              - profile
              - read
            client-name: client-app
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9001"